name: PortManager Compiler
run-name: PortManager backend compiling
on: [push]
jobs:
  PortManager-Compile:
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
          - platform: linux/arm64
            runner: ubuntu-24.04

    runs-on: ${{matrix.runner}}
    steps:
      - name: install libraries
        run: |
          sudo apt install libmariadb-dev cmake -y
      - name: clone repository
        uses: actions/checkout@v4
      - name: copy files
        run: |
          cp -r ${{github.workspace}}/* ~/
      - name: run cmake
        run: |
          mkdir build
          cd build
          cmake ..
      - name: run make
        run: |
          cd build
          make
          platform=${{matrix.platform}}
          mv PortManager_backend ~/${platform:6}
          ls -la ~/
      - name: upload file
        uses: actions/upload-artifact@v3
        with:
          name: upload-file
          path: ~/${{matrix.platform}}
  make-release:
    runs-on: ubuntu-latest
    needs: PortManager-Compile
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3

      - name: ls
        run: |
          ls -la

