name: PortManager Compiler
run-name: PortManager backend compiling
on: [push]
jobs:
  PortManager-Compile:
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
          - platform: linux/arm64
            runner: debian12-arm64

    runs-on: ${{matrix.runner}}
    steps:
      - name: install libraries
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install libmariadb-dev cmake -y
          sudo apt autoremove -y
      - name: clone repository
        uses: actions/checkout@v4
      - name: copy files
        run: |
          cp -r ${{github.workspace}}/* ~/
      - name: run cmake
        run: |
          mkdir build
          cd build
          cmake ..
      - name: run make
        id: generate-file-name
        run: |
          cd build
          make
          
          echo '::set-output name=result::${{matrix.runner}}-'$(arch)
          ls -la

      - name: login ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CLASSIC_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/mccbena/portmanagerbackend